language: objective-c

# if test available use this config istead of a custom script
#xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
#xcode_project: <%= name %>.xcodeproj 
# or use 
# xcode_workspace: <%= name %>.xcworkspace 

#xcode_scheme: <%= name %>

script:
  - xcodebuild -scheme <%= name %> -workspace <%= name %>.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=12.1' build