version: "3.1"

networks:
  proxy-net:
    external:
      name: proxy-net

services:
  <%= name %>:
    container_name: <%= name %>
    networks:
      - proxy-net
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=<%= name %>.viktor-braun.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=<%= name %>.viktor-braun.de
      - LETSENCRYPT_EMAIL=mail@viktor-braun.de
